//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkillsEntities : DbContext
    {
        private static WorldSkillsEntities context;
        public WorldSkillsEntities()
            : base("name=WorldSkillsEntities")
        {
        }
        public static WorldSkillsEntities GetContext() {
            if (context == null)
                context = new WorldSkillsEntities();
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
